// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import ClientLogos from "./ClientLogos/index.svelte";
import ContactCard from "./ContactCard/index.svelte";
import CtaBanner from "./CtaBanner/index.svelte";
import CtaBlock from "./CtaBlock/index.svelte";
import EmployeeApplication from "./EmployeeApplication/index.svelte";
import FullWidthImage from "./FullWidthImage/index.svelte";
import Headline from "./Headline/index.svelte";
import Hero from "./Hero/index.svelte";
import IntakeForm from "./IntakeForm/index.svelte";
import LeadStatement from "./LeadStatement/index.svelte";
import LeadText from "./LeadText/index.svelte";
import Leadership from "./Leadership/index.svelte";
import MediaText from "./MediaText/index.svelte";
import OurPlan from "./OurPlan/index.svelte";
import PageHero from "./PageHero/index.svelte";
import PhaseBubbles from "./PhaseBubbles/index.svelte";
import PhaseDetail from "./PhaseDetail/index.svelte";
import PhaseSlider from "./PhaseSlider/index.svelte";
import ProjectList from "./ProjectList/index.svelte";
import QuoteSlider from "./QuoteSlider/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import SectorCards from "./SectorCards/index.svelte";
import SectorFeature from "./SectorFeature/index.svelte";
import StatementBand from "./StatementBand/index.svelte";
import Testimonial from "./Testimonial/index.svelte";
import TextColumns from "./TextColumns/index.svelte";
import VideoBand from "./VideoBand/index.svelte";

export const components = {
  accordion: Accordion,
  client_logos: ClientLogos,
  contact_card: ContactCard,
  cta_banner: CtaBanner,
  cta_block: CtaBlock,
  employee_application: EmployeeApplication,
  full_width_image: FullWidthImage,
  headline: Headline,
  hero: Hero,
  intake_form: IntakeForm,
  lead_statement: LeadStatement,
  lead_text: LeadText,
  leadership: Leadership,
  media_text: MediaText,
  our_plan: OurPlan,
  page_hero: PageHero,
  phase_bubbles: PhaseBubbles,
  phase_detail: PhaseDetail,
  phase_slider: PhaseSlider,
  project_list: ProjectList,
  quote_slider: QuoteSlider,
  rich_text: RichText,
  section_grid: SectionGrid,
  sector_cards: SectorCards,
  sector_feature: SectorFeature,
  statement_band: StatementBand,
  testimonial: Testimonial,
  text_columns: TextColumns,
  video_band: VideoBand,
};
